version: '3.8'

networks:
  neo4j-network:
    driver: bridge

services:
  mongodb:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    volumes:
      - ${MONGODB_DATA}:/data/db

  mongo-seed:
    image: mongo:7.0
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
    env_file:
      - .env.mongo_seed
    profiles: ['load-data']

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env.mongo_express
    links:
      - mongodb
    profiles: ['full']

  neo4j:
    image: neo4j:5.20.0
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ${NEO4J_DATA}:/data
      - ./neo4j/plugins:/plugins
    env_file:
      - .env.neo4j
    profiles: ['basic', 'full']
    networks:
      - neo4j-network
