name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.yaml'
      - 'Dockerfile'
      - 'src/**'
      - 'frontend/data2graph/**'
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Inventory Image"
        run: make push_images
